import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://flexipill-ui-new-staging.vercel.app/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByPlaceholder('Enter your number', { exact: true }).click();
  await page.getByPlaceholder('Enter your number', { exact: true }).fill('1111111111');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('1');
  await page.getByRole('textbox').nth(1).fill('1');
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).fill('1');
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByText('Manage Address').click();
  await page.getByRole('button', { name: '+ Add Address' }).click();
  await page.getByLabel('Name *').click();
  await page.getByLabel('Name *').fill('gaurav');
  await page.getByLabel('Phone number *').click();
  await page.getByLabel('Phone number *').fill('7082813625');
  await page.getByLabel('House No. / Building *').click();
  await page.getByLabel('House No. / Building *').fill('745');
  await page.getByLabel('Locality *').click();
  await page.getByLabel('Locality *').fill('Urban Estate - 2');
  await page.getByLabel('Pincode *').click();
  await page.getByLabel('Pincode *').fill('125001');
  await page.getByRole('group', { name: 'Address Type' }).click();
  await page.getByText('Home', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});